---
roles:
  master201621:
    provisioners:
      - type: pe_bootstrap
        role: :master
        version: '2016.2.1'

  agent_201621:
    provisioners:
      - type: pe_bootstrap
        #version: '2016.2.0'
        master: 'master201621-centos'
